### ISSUE TITLE
Does not seem to work with cucumber 1.0.0

### ISSUE THREAD

**Issue by kirill-onufrienko-db** [cube-io/teamcity-formatter#3]
TypeError: node_modules\teamcity-formatter\lib\listenForStepsAndFormatForTeamcity.js:11 stepResult.isSuccessful is not a function
  at handleStepResult (F:[censored]\listenForStepsAndFormatForTeamcity.js:23:29)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by ath88** [comment]
Thanks for the report. We are slowly moving away from teamcity, but we would love to merge a pull request if you fix the issue. :)

**Comment by lsantos10** [comment]
What is the expected cucumber version where this can work?

**Comment by kirill-onufrienko-db** [comment]
When I've raised an issue it was found in integration with cucumber-js 1.0.0
I did not check the compatibility with 2.0.0-rc.6 which is now the current latest version but I suppose it's worth checking it's compatible.
